units:
  # Proxy Spacing Variables
  kx: u
  ky: u
  # Padding Variables
  px: kx + 2
  py: ky + 2

points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          rows:
            bottom.skip: true
            top.skip: true
            home:
              key:
                width: 1.5ky
                rotate: 60
        pinky:
          key.stagger: 0
        ring:
          key.stagger: 10
        middle:
          key.stagger: 6.5
        index:
          key.stagger: -6.5
        inner:
          key.stagger: -2.5
      rows:
        bottom:
        home:
        top:

    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-4.7, -21.7]
      columns:
        inner:
        middle:
          key:
            shift: [20.9 - ky, -1.27]
            rotate: -10
        outer:
          key:
            shift: [41.2 - 2ky, -6.9]
            rotate: -23
      rows:
        cluster:
