units:
  # Proxy Spacing Variables
  kx: u
  ky: u
  # Padding Variables
  px: kx + 2
  py: ky + 2

points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          rows:
            mod.skip: true
            bottom.skip: true
            top.skip: true
        pinky:
          rows.mod.skip: true
          key.stagger: 0
        ring:
          rows.mod.skip: true
          key.stagger: 10
        middle:
          rows.mod.skip: true
          key.stagger: 6.5
        index:
          rows.mod.skip: true
          key.stagger: -6.5
        inner:
          rows.mod.skip: true
          key.stagger: -2.5
      rows:
        mod:
        bottom:
        home:
        top:

    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_mod
        shift: [-4, -4]
      columns:
        inner:
        middle:
          key:
            splay: -10
            shift: [2, -1.5]
        outer:
          key:
            splay: -20
            shift: [6, -3]
      rows:
        cluster:
